export const productos = [{id:1,nombre:"pantalon cuerina",marca:" ",etiqueta:"no",talle:"S",precio:"6000"},
{id:2,nombre:"pantalon jean negro",marca:" ",etiqueta:"no",talle:"S",precio:"6000"},
{id:3,nombre:"jean",marca:" ",etiqueta:"no",talle:"S",precio:"10000"},
{id:4,nombre:"jean roto",marca:" ",etiqueta:"no",talle:"S",precio:"10000"},
{id:5,nombre:"jean roto",marca:" ",etiqueta:"no",talle:"S",precio:"10000"},
{id:6,nombre:"jean roto",marca:" ",etiqueta:"no",talle:"S",precio:"6000"},
{id:7,nombre:"negro cinto pantalon",marca:" ",etiqueta:"no",talle:"S",precio:"6000"},
{id:8,nombre:"pantalon beige",marca:"forever21",etiqueta:"no",talle:"S",precio:"10000"},
{id:9,nombre:"pantalon jaspeeado negro",marca:" ",etiqueta:"no",talle:"S",precio:"12000"},
{id:10,nombre:"pantalon negro zara",marca:"zara",etiqueta:"no",talle:"S",precio:"17000"},
{id:11,nombre:"pantalon old navy con etiqueta",marca:" ",etiqueta:"si",talle:"2",precio:"15000"},
{id:12,nombre:"calza franja",marca:" ",etiqueta:"no",talle:"S",precio:"6000"},
{id:13,nombre:"pollera ban be",marca:"ban be",etiqueta:"si",talle:"M",precio:"10000"},
{id:14,nombre:"short agujeros",marca:"agnue",etiqueta:"si",talle:"S",precio:"6000"},
{id:15,nombre:"jean zara",marca:"zara",etiqueta:"no",talle:"S",precio:"10000"},
{id:16,nombre:"chaleco gris",marca:" ",etiqueta:"no",talle:"M",precio:"6000"},
{id:17,nombre:"jean american mix negro",marca:"american mix",etiqueta:"no",talle:"S",precio:"10000"},
{id:18,nombre:"buzo good babes",marca:" ",etiqueta:"no",talle:"S",precio:"7000"},
{id:19,nombre:"jean roto",marca:" ",etiqueta:"no",talle:"M",precio:"5000"},
{id:20,nombre:"jean pull and bear con etiqueta",marca:"pull and bear",etiqueta:"si",talle:"S",precio:"18000"},
{id:21,nombre:"corpiño victoria secret con etiqueta",marca:"victoria secret",etiqueta:"si",talle:"32 B",precio:"20000"},
{id:22,nombre:"jean pull and bear",marca:"pull and bear",etiqueta:"no",talle:"S",precio:"18000"},
{id:23,nombre:"pollera hey black",marca:"hey black",etiqueta:"si",talle:"M",precio:"10000"},
{id:24,nombre:"short kiwano",marca:"kiwano",etiqueta:"no",talle:"S",precio:"6000"},
{id:25,nombre:"pantalon rallado",marca:" ",etiqueta:"no",talle:"S",precio:"6000"},
{id:26,nombre:"calza elefantes",marca:" ",etiqueta:"no",talle:"M",precio:"5000"},
{id:27,nombre:"calza negra forever",marca:"forever21",etiqueta:"no",talle:"S",precio:"10000"},
{id:28,nombre:"calza gris forever",marca:"forever21",etiqueta:"no",talle:"S",precio:"10000"},
{id:29,nombre:"pantalon forever piyama",marca:" ",etiqueta:"no",talle:"S",precio:"10000"},
{id:30,nombre:"short pollera",marca:" ",etiqueta:"no",talle:"S",precio:"6000"},
{id:31,nombre:"short pollera",marca:" ",etiqueta:"no",talle:"S",precio:"6000"},
{id:32,nombre:"short cuerina",marca:"awai",etiqueta:"si",talle:"S",precio:"10000"},
{id:33,nombre:"short pollera kiwano",marca:"kiwano",etiqueta:"si",talle:"S",precio:"10000"},
{id:34,nombre:"short pollera kiwano",marca:" ",etiqueta:"no",talle:"S",precio:"6000"},
{id:35,nombre:"short cuerina",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:36,nombre:"pollera cinto",marca:" ",etiqueta:"no",talle:"XS",precio:"6000"},
{id:37,nombre:"top blanco",marca:"forever21",etiqueta:"no",talle:"S",precio:"6000"},
{id:38,nombre:"short pollera brillos",marca:" ",etiqueta:"no",talle:"S",precio:"6000"},
{id:39,nombre:"short blanco",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:40,nombre:"short pollera blanco",marca:" ",etiqueta:"no",talle:"XS",precio:"5000"},
{id:41,nombre:"short pollera negro",marca:" ",etiqueta:"no",talle:"S",precio:"6000"},
{id:42,nombre:"short pollera blanco",marca:" ",etiqueta:"no",talle:"S",precio:"6000"},
{id:43,nombre:"pantalon cuerina negro",marca:" ",etiqueta:"no",talle:"S",precio:"10000"},
{id:44,nombre:"short pollera negro",marca:" ",etiqueta:"no",talle:"S",precio:"6000"},
{id:45,nombre:"short pollera negro",marca:" ",etiqueta:"no",talle:"S",precio:"6000"},
{id:46,nombre:"pollera negra",marca:" ",etiqueta:"no",talle:"S",precio:"6000"},
{id:47,nombre:"buzo gris",marca:" ",etiqueta:"no",talle:"S",precio:"10000"},
{id:48,nombre:"wide blanco pantalon",marca:" ",etiqueta:"no",talle:"38",precio:"18000"},
{id:49,nombre:"bralete blanco",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:50,nombre:"top negro",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:51,nombre:"short pollera negro",marca:" ",etiqueta:"no",talle:"S",precio:"6000"},
{id:52,nombre:"short blanco",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:53,nombre:"top blanco",marca:" ",etiqueta:"no",talle:"M",precio:"5000"},
{id:54,nombre:"VS negro",marca:"victoria secret",etiqueta:"no",talle:"32 B",precio:"10000"},
{id:55,nombre:"VS beige",marca:"victoria secret",etiqueta:"no",talle:"32 B",precio:"10000"},
{id:56,nombre:"top gris",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:57,nombre:"cartera beige",marca:" ",etiqueta:"no",talle:"S",precio:"7000"},
{id:58,nombre:"carterita prune",marca:"prune",etiqueta:"no",talle:"S",precio:"15000"},
{id:59,nombre:"top blanco",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:60,nombre:"bikini compañia del sol",marca:"comp del sol",etiqueta:"no",talle:"S",precio:"20000"},
{id:61,nombre:"top 1 manga",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:62,nombre:"guantes bici",marca:" ",etiqueta:"no",talle:"S",precio:"10000"},
{id:63,nombre:"VS blanco",marca:"victoria secret",etiqueta:"no",talle:"32 B",precio:"10000"},
{id:64,nombre:"top blanco",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:65,nombre:"top marron",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:66,nombre:"top blanco B",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:67,nombre:"top negro",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:68,nombre:"top negro reversible",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:69,nombre:"body",marca:"julieta",etiqueta:"si",talle:"S",precio:"10000"},
{id:70,nombre:"VS negro",marca:"victoria secret",etiqueta:"no",talle:"32 B",precio:"5000"},
{id:71,nombre:"musculosa",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:72,nombre:"top blanco",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:73,nombre:"vestido fiesta largo",marca:"bera",etiqueta:"si",talle:"L",precio:"50000"},
{id:74,nombre:"bolso rallado",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:75,nombre:"remera new balance",marca:"new balance",etiqueta:"no",talle:"XL",precio:"10000"},
{id:76,nombre:"camisa HyM",marca:"HyM",etiqueta:"no",talle:"XS",precio:"12000"},
{id:77,nombre:"remera fila",marca:"fila",etiqueta:"no",talle:"M",precio:"10000"},
{id:78,nombre:"top nike",marca:"nike",etiqueta:"no",talle:"S",precio:"15000"},
{id:79,nombre:"pollera etiqueta de la ostia",marca:"de la ostia",etiqueta:"si",talle:"38",precio:"20000"},
{id:80,nombre:"campera forever",marca:"forever21",etiqueta:"no",talle:"S",precio:"20000"},
{id:81,nombre:"calza deportiva",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:82,nombre:"remera beige",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:83,nombre:"body negro",marca:" ",etiqueta:"no",talle:"XS",precio:"5000"},
{id:84,nombre:"top negro",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:85,nombre:"short blanco",marca:" ",etiqueta:"no",talle:"S",precio:"6000"},
{id:86,nombre:"body negro",marca:" ",etiqueta:"no",talle:"S",precio:"6000"},
{id:87,nombre:"bachino remera",marca:"bachino",etiqueta:"no",talle:"S",precio:"5000"},
{id:88,nombre:"top negro cruzado",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:89,nombre:"top negro",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:90,nombre:"top blanco",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:91,nombre:"top gris forever",marca:"forever21",etiqueta:"no",talle:"S",precio:"5000"},
{id:92,nombre:"top negro",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:93,nombre:"bomber",marca:" ",etiqueta:"no",talle:"M",precio:"20000"},
{id:94,nombre:"camisa bachino",marca:"bachino",etiqueta:"no",talle:"XS",precio:"5000"},
{id:95,nombre:"montgomery",marca:"aeropostale",etiqueta:"no",talle:"M",precio:"35000"},
{id:96,nombre:"buzo zara",marca:"zara",etiqueta:"no",talle:"S",precio:"15000"},
{id:97,nombre:"buzo aeropostale",marca:"aeropostale",etiqueta:"no",talle:"S",precio:"18000"},
{id:98,nombre:"remera blanca",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:99,nombre:"sweater blanco",marca:" ",etiqueta:"no",talle:"M",precio:"15000"},
{id:100,nombre:"calza verde",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:101,nombre:"top negro",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:102,nombre:"camisa pull and bear",marca:"pull and bear",etiqueta:"no",talle:"S",precio:"12000"},
{id:103,nombre:"top de la ostia",marca:"de la ostia",etiqueta:"no",talle:"S",precio:"5000"},
{id:104,nombre:"top brillo",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:105,nombre:"corpiño kiwano",marca:"kiwano",etiqueta:"no",talle:"S",precio:"5000"},
{id:106,nombre:"top deportivo",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:107,nombre:"remera negra",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:108,nombre:"calza forever",marca:"forever21",etiqueta:"si",talle:"S",precio:"12000"},
{id:109,nombre:"biker negra",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:110,nombre:"calza adidas",marca:"adidas",etiqueta:"no",talle:"S",precio:"12000"},
{id:111,nombre:"calza adidas",marca:"adidas",etiqueta:"no",talle:"S",precio:"12000"},
{id:112,nombre:"calza negra",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:113,nombre:"calza verde",marca:" ",etiqueta:"no",talle:"S",precio:"5000"},
{id:114,nombre:"blazer negro",marca:" ",etiqueta:"no",talle:"M",precio:"10000"},
{id:115,nombre:"piloto cuesta blanca",marca:"cuesta blanca",etiqueta:"no",talle:"42",precio:"17000"},
{id:116,nombre:"campera jean",marca:" ",etiqueta:"no",talle:"S",precio:"15000"},
{id:117,nombre:"tapado negro",marca:" ",etiqueta:"no",talle:"M",precio:"20000"},
{id:118,nombre:"mono negro",marca:"HyM",etiqueta:"no",talle:"S",precio:"6000"},
{id:119,nombre:"buzo verde",marca:"HyM",etiqueta:"no",talle:"S",precio:"6000"},
{id:120,nombre:"buzo gris cuello",marca:"kiwano",etiqueta:"no",talle:"M",precio:"5000"},
{id:121,nombre:"remera gris",marca:"forever21",etiqueta:"no",talle:"S",precio:"5000"},
{id:122,nombre:"buzo marron forever",marca:"forever21",etiqueta:"no",talle:"S",precio:"6000"},
{id:123,nombre:"top negro boho",marca:" ",etiqueta:"no",talle:"M",precio:"6000"},
{id:124,nombre:"sueter negro",marca:" ",etiqueta:"no",talle:"M",precio:"5000"},
{id:125,nombre:"blazer blanco",marca:" ",etiqueta:"no",talle:"M",precio:"10000"},
{id:126,nombre:"biker negra",marca:" ",etiqueta:"no",talle:"M",precio:"5000"},
{id:127,nombre:"sueter pull and bear beige",marca:"pull and bear",etiqueta:"no",talle:"XS",precio:"15000"},
{id:128,nombre:"Camisa blanca",marca:" ",etiqueta:"no",talle:"M",precio:"6000"}]